### PR TITLE
Issue #45 (added missing submodule to setup).

### PR DESCRIPTION
**Pull request by nsaphra**

### CODE REVIEW

**Comment by piskvorky** [comment]
Any reason not to simply use `setuptools.find_packages()`?

**Comment by nsaphra** [comment]
None whatsoever, I'm just not much of a Python programmer. Thanks for the tip, @piskvorky, I'm modifying the branch.

**Comment by maciejkula** [comment]
Thanks for your help guys!

@nsaphra it would be great if you could add a test for this too. That way CI can pick up on any regressions in the future (by the way, ignore Travis. I need to disable it.)

**Comment by nsaphra** [comment]
@maciejkula I don't have time to write tests right now, but if you want to merge in this PR now, I can add writing tests to my leisure time queue.

**Comment by nsaphra** [comment]
I did test it locally by running the example analogy script, I just don't have time to write automated tests for the metrics right now.

**Comment by maciejkula** [comment]
OK, I'll write a test. I'll probably merge this and add a test tonight. Thanks for the fix!

**Comment by nsaphra** [comment]
Ping! This is a pretty basic change that restores the evaluation functions in the module, so I'm not sure it needs extra testing right now.

**Pull request merged**
